# Generated by Django 4.2 on 2025-04-04 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(7)])),
                ('especialidade', models.CharField(choices=[('CAR', 'Cardiologista'), ('ORT', 'Ortopedista'), ('GO', 'Ginecologista Obstreta')], max_length=20)),
                ('crm', models.CharField(max_length=7, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
